<?php

namespace Tests\Unit;

use App\Services\LinkService;
use GuzzleHttp\Client;
use PHPUnit\Framework\TestCase;

class LinkServiceTest extends TestCase
{
	protected LinkService $linkService;
	
	protected function setUp(): void
	{
		parent::setUp(); // TODO: Change the autogenerated stub
		$client = new Client();
		$this->linkService = new LinkService($client);
	}
	
	public function test_link_service_check_tag_return_true(): void
	{
		$result = $this->linkService->checkIfTagExists(['api']);
		$this->assertTrue($result);
	}
	
	public function test_link_service_check_tag_return_false(): void
	{
		$result = $this->linkService->checkIfTagExists(['test']);
		$this->assertFalse($result);
	}
	
	public function test_link_service_add_tags_responses_empty(): void
	{
		$result = $this->linkService->addTagsAndGetIds([]);
		$this->assertEmpty($result);
	}
}
